# 1. 예외 처리

## 1.1. 오류의 종류
오류는 크게 두 가지 종류로 나눌 수 있다. 프로그래밍 언어를 기계어로 변역하는 과정에서 발생하는 컴파일 오류(Compile Error) 와 실행 도중에 예기치 못하게 발생하는 실행 오류(RunTime Error)로 나눈다. 
- Compile Error : 기계어로 번역되는 과정에서 발생하는 문법적인 오류를 의미한다.
- RunTime Error : 프로그램이 실행되는 도중에 예기치 못하게 발생하는 오류를 의미한다.

이중에 우리가 예외처리를 해야하는 것은 **실행오류(Runtime Error)**이다.

## 1.2. 예외 처리

### 1) try-catch 문
가장 기본적인 예외 처리 방법이다. try 구문의 소스 코드를 수행하다가 오류가 발생하면 catch 문으로 빠진다. catch 문에는 괄호가 존재하는데, 이 때 오류의 종류를 지정할 수 있다. 이 때 상위 클래스의 오류가 맨 뒤의 catch 문에 오도록 작성하여야 한다. 만약 상위 클래스의 Exception이 제일 처음에 작성되어 있으면, 이후에 작성한 catch 문에는 도달할 수 없다.

```java
/** try-catch문을 잘 사용한 예시 **/
try { 
  // Error 가 발생할 수 있는 소스 코드
} catch (NullPointerException e1) {  
  // NPE가 발생하였을 경우에만 해당 catch 문으로 빠짐
} catch (Exception e2) {
  // 앞의 에러가 발생한 것이 아니라면 두번째 catch 문으로 빠짐
}

/** try-catch문을 잘못 사용한 예시 **/
try { 
  // Error 가 발생할 수 있는 소스 코드
} catch (Exception e1) {  
  // 최상위 Exception이므로 모든 Exception 발생시 해당 catch 문으로 빠짐
} catch (NullPointerException e2) {
  // 도달할 수 없는 catch 문 소스 코드
}
```

### 2) try-catch-finally 문
try-catch-finally 문은 try-catch문과 비슷하다. try-catch 문을 앞선 단계와 같이 통과하고, 마지막으로 finally 구문을 반드시 (Error 가 발생했을 때와 안 발생하였을 때) 수행한다. 이런 코드를 어떻게 작성할 수 있을까? 바로 Resource 관련하여 사용할 때 유용할 것이다. 아래의 예시는 각각 try-catch 문만을 사용한 예시와 try-catch-finally를 사용한 예시이다.

```java
/** try-catch 문 만을 이용한 소스 코드 **/
try {
  fis = new FileInputStream("a.txt");
  if(fis != null) {
    try {
      fis.close();
     } catch (IOException e) {
      // fis.close()를 수행하며 오류가 발생할 때 수행되는 에러
     }
  }
} catch (FileNotFoundException e) {
  // a.txt 를 찾지 못했을 경우 발생하는 Exception
}
```

```java
/** try-catch-finally 를 이용한 소스 코드 **/
try {
  fis = new FileInputStream("a.txt");
} catch (FileNotFoundException e) {
  // a.txt 를 찾지 못했을 경우 발생하는 Exception
} finally {
  if(fis != null) {
    try {
      fis.close();
    } catch (IOException e) {
      // IOException 이 발생할 경우 수행되는 소스코드
    }
  }
}
```

### 3) try-with-resource 문
앞서 살펴봤듯이 시스템 리소스를 사용하고 해제하는 코드는 다소 복잡하다. 자바 7부터는 시스템 리소스를 위한 try-with-resource 문을 제공한다. 이를 통해서 close()를 명시적으로 호출하지 않아도 close() 메서드를 명시적으로 호출하여 준다. 아래와 같이 사용할 리소스를 선언하면 AutoCloseable 인터페이스가 자동으로 close() 메서드를 호출하여 준다.

```java
/** Auto Closeable Interface 선언 **/
public class AutoCloseObj implements AutoClosable {
  @Override
  public void close() thrwos Exception {
    System.out.println("Resource is Closed.");
  }
}
```

```java
/** try-with-resource 사용 **/
public class AutoCloseTest {
  public static void main(String[] args) {
    try(AutoCloseObj obj = new AutoCloseObj()) {
      // 해당 부분에서 에러 발생한다고 가정
    } catch(Exception e) {
      System.out.println("Exception Occurred.");
    }
}

// 결과 
// Exception Occurred.
// Resource is Closed.
```
## 1.3. 예외 처리 미루기
Throws 를 통하여 예외 처리를 미룰 수 있다. 예외를 처리하지 않고 미룬다고 선언을 한다면, 그 메서드를 호출하여 사용하는 부분에서 예외 처리를 해야한다. 

## 1.4. 사용자 정의 예외 처리

#### 사용자 정의 예외 구현
```java 
public class IDFormatException extends Exception {
  public IDFormatException(String message) {
    super(message);
  }
}
```

#### 사용자 정의 예외 테스트
```java
public class IDFormatTest {
  private String userID;
  
  public String getUserID() {
    return userID;
  }
  
  public void setUserID(String userID) throws IDFormatException {
    if(userID == null) {
      throw new IDFormatException("아이디는 null일 수 없습니다.");
    }
    else if(userID.length() < 8 || userID.length() > 20) {
      throw new IDFormatException("아이디는 8자 이상 20자 이하로 쓰세요.");
    }
    this.userID = userID;
  }
  
  public static void main(String[] args) {
    IDFormatTest test = new IDFormatTest();
    
    String userID = null;
    try {
      test.setUserID(userID);
    } catch (IDFormatException e) {
      System.out.println(e.getMessage());
    }
    
    userID = "1234567";
    try {
      test.setUserID(userID);
    } catch (IDFormatException e) {
      System.out.println(e.getMessage());
    }
  }
}
```

#### 결과
```
아이디는 null일 수 없습니다.
아이디는 8자 이상 20자 이하로 쓰세요.
```

## 1.5. 결론
프로그램을 개발할 때는 로그를 남기는 것이 중요하다. 오류가 발생했을 때 로그를 보고 오류가 발생하는 코드를 순서대로 따라가며 확인할 수 있고, 원인을 찾을 수 있기 때문이다. 금일 습득한 예외 처리 방법과 함께 로그를 남긴다면 예외가 발생하였을 때 그 원인을 유추하여 버그를 보다 수월하게 잡을 수 있을 것이다.







